field: 9971101b-a2d6-497e-af1c-b041ad6237f5
fieldLayouts:
  b144a770-1f27-4b7a-b3a3-a6b0bd7a27b5:
    tabs:
      -
        fields:
          9a066578-5edd-4e1e-b7c3-72621a7cb09e:
            required: false
            sortOrder: 2
          cd458fa2-9dd3-4f22-8f29-ffcf4c608976:
            required: true
            sortOrder: 3
          f54c93a7-f46e-4919-b5bb-ae51aba46ba7:
            required: true
            sortOrder: 1
        name: Content
        sortOrder: 1
fields:
  9a066578-5edd-4e1e-b7c3-72621a7cb09e:
    contentColumnType: text
    fieldGroup: null
    handle: streetLine2
    instructions: ''
    name: 'Street (line 2/unit)'
    searchable: true
    settings:
      charLimit: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  cd458fa2-9dd3-4f22-8f29-ffcf4c608976:
    contentColumnType: text
    fieldGroup: null
    handle: cityStateZip
    instructions: ''
    name: 'City, State, Zip'
    searchable: true
    settings:
      charLimit: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  f54c93a7-f46e-4919-b5bb-ae51aba46ba7:
    contentColumnType: text
    fieldGroup: null
    handle: streetLine1
    instructions: ''
    name: 'Street (line 1)'
    searchable: true
    settings:
      charLimit: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: address
name: address
sortOrder: 1
