field: 4ff032c1-a872-4d02-93f9-dfeaefe198fe
fieldLayouts:
  521a2f52-d1bd-45f9-be5d-f409d07d311a:
    tabs:
      -
        fields:
          758fb4e2-a135-44cf-911e-bb691953d0ad:
            required: false
            sortOrder: 2
          8b6e338c-6267-45e7-9523-e319e87213dc:
            required: false
            sortOrder: 1
        name: Content
        sortOrder: 1
fields:
  758fb4e2-a135-44cf-911e-bb691953d0ad:
    contentColumnType: string
    fieldGroup: null
    handle: sectionContent
    instructions: ''
    name: 'Section Content'
    searchable: true
    settings:
      availableTransforms: ''
      availableVolumes: ''
      cleanupHtml: '1'
      columnType: text
      configFile: ''
      purifyHtml: '1'
    translationKeyFormat: null
    translationMethod: site
    type: craft\redactor\Field
  8b6e338c-6267-45e7-9523-e319e87213dc:
    contentColumnType: text
    fieldGroup: null
    handle: sectionTitle
    instructions: ''
    name: 'Section Title'
    searchable: true
    settings:
      charLimit: ''
      columnType: text
      initialRows: '2'
      multiline: '1'
      placeholder: ''
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\PlainText
handle: contentSection
name: 'Content Section'
sortOrder: 1
