field: dd868fe1-3a50-4146-be40-157b12e3f0dc
fieldLayouts:
  fa776157-058a-4960-8fb3-a5459ad81c4f:
    tabs:
      -
        fields:
          b46a8673-1633-4d61-b2b0-d99f2ecf7b97:
            required: false
            sortOrder: 1
          e50f468c-4a51-414d-b653-e8b9b143aec2:
            required: true
            sortOrder: 2
        name: Content
        sortOrder: 1
fields:
  b46a8673-1633-4d61-b2b0-d99f2ecf7b97:
    contentColumnType: boolean
    fieldGroup: null
    handle: expanded
    instructions: 'Setting this field to "on" will make the image carousel expand outside the content container.'
    name: 'Expanded?'
    searchable: true
    settings:
      default: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
  e50f468c-4a51-414d-b653-e8b9b143aec2:
    contentColumnType: string
    fieldGroup: null
    handle: images
    instructions: ''
    name: Images
    searchable: true
    settings:
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:cd389634-6297-4886-ac1a-17f7ff2050c8'
      defaultUploadLocationSubpath: ''
      limit: ''
      localizeRelations: ''
      restrictFiles: '1'
      selectionLabel: 'Add an image'
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:1e3bbacb-6818-4f7f-8516-ae22e47c8b82'
      singleUploadLocationSubpath: '{owner.slug}'
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: true
      validateRelatedElements: ''
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: imageCarousel
name: 'Image Carousel'
sortOrder: 4
