field: dd868fe1-3a50-4146-be40-157b12e3f0dc
fieldLayouts:
  366bfc65-39af-4a15-ae3e-6bcbc88909a9:
    tabs:
      -
        fields:
          b9756ed3-dc3f-4edb-9008-5fe361c36fc0:
            required: false
            sortOrder: 2
          e59107c8-273a-4ce2-a1a1-9809e9f36e6a:
            required: false
            sortOrder: 1
        name: Content
        sortOrder: 1
fields:
  b9756ed3-dc3f-4edb-9008-5fe361c36fc0:
    contentColumnType: boolean
    fieldGroup: null
    handle: expanded
    instructions: 'Setting this field to "on" will make the image block expand outside the content container.'
    name: 'Expanded?'
    searchable: true
    settings:
      default: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
  e59107c8-273a-4ce2-a1a1-9809e9f36e6a:
    contentColumnType: string
    fieldGroup: null
    handle: images
    instructions: 'Add one image, or multiple images.'
    name: Image(s)
    searchable: true
    settings:
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:cd389634-6297-4886-ac1a-17f7ff2050c8'
      defaultUploadLocationSubpath: ''
      limit: ''
      localizeRelations: ''
      restrictFiles: '1'
      selectionLabel: 'Add an image'
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:1e3bbacb-6818-4f7f-8516-ae22e47c8b82'
      singleUploadLocationSubpath: '{owner.slug}'
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: true
      validateRelatedElements: ''
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: imageBlock
name: 'Image Block'
sortOrder: 3
