field: 15eeedeb-4db5-4499-b869-f35d749fa2c5
fieldLayouts:
  a0334cfd-f6de-4090-ba98-542ab5afb2b6:
    tabs:
      -
        fields:
          2afcb311-2eb9-4815-aa4f-f2b64ec68e58:
            required: false
            sortOrder: 1
          7fd2d5fc-5eb7-4da7-ae38-e5451a68b129:
            required: false
            sortOrder: 2
        name: Content
        sortOrder: 1
fields:
  2afcb311-2eb9-4815-aa4f-f2b64ec68e58:
    contentColumnType: text
    fieldGroup: null
    handle: sectionTitle
    instructions: ''
    name: 'Section Title'
    searchable: true
    settings:
      charLimit: ''
      code: ''
      columnType: text
      initialRows: '1'
      multiline: '1'
      placeholder: ''
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\PlainText
  7fd2d5fc-5eb7-4da7-ae38-e5451a68b129:
    contentColumnType: text
    fieldGroup: null
    handle: sectionContent
    instructions: ''
    name: 'Section Content'
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      cleanupHtml: true
      columnType: text
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: ''
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
    translationKeyFormat: null
    translationMethod: site
    type: craft\redactor\Field
handle: introSection
name: 'Intro Section'
sortOrder: 1
