field: 3c5b1db6-07cb-449e-991f-2bcbf56ce465
fieldLayouts:
  e888db06-50bf-48d1-92b8-345acf202bdf:
    tabs:
      -
        fields:
          2d242bfb-1cd4-40db-b359-9c0442cde7d5:
            required: true
            sortOrder: 2
          3459d9c3-35a6-4335-8967-4ae87455f584:
            required: false
            sortOrder: 3
          5c0c1ca2-0bdf-4792-903a-67132bcb8de2:
            required: false
            sortOrder: 7
          80a2f43e-be4c-4565-bfbe-5efdea8aad68:
            required: true
            sortOrder: 1
          8ac9d37c-4f05-486a-84e6-2d59838d6ccb:
            required: false
            sortOrder: 6
          9b679f54-11f0-4985-975f-c94a316e3a2a:
            required: false
            sortOrder: 5
          b0cf3b3c-aac9-48d9-8c70-6b77edb044da:
            required: false
            sortOrder: 4
          d67b0672-6bc9-4767-9024-9006ff629216:
            required: false
            sortOrder: 9
          ea18bac6-1587-4544-903f-15082de1333e:
            required: false
            sortOrder: 8
        name: Content
        sortOrder: 1
fields:
  2d242bfb-1cd4-40db-b359-9c0442cde7d5:
    contentColumnType: text
    fieldGroup: null
    handle: description
    instructions: ''
    name: Description
    searchable: true
    settings:
      charLimit: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: ''
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\PlainText
  3459d9c3-35a6-4335-8967-4ae87455f584:
    contentColumnType: integer(10)
    fieldGroup: null
    handle: monthlyPayment
    instructions: 'The monthly payment amount'
    name: 'Monthly Payment'
    searchable: true
    settings:
      decimals: '0'
      max: ''
      min: '0'
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Number
  5c0c1ca2-0bdf-4792-903a-67132bcb8de2:
    contentColumnType: text
    fieldGroup: null
    handle: yearlyPaymentStripePlanId
    instructions: 'The Stripe plan ID assigned to the corresponding subscription plan (ex: ''p001'')'
    name: 'Yearly Payment Stripe Plan Id'
    searchable: true
    settings:
      charLimit: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  80a2f43e-be4c-4565-bfbe-5efdea8aad68:
    contentColumnType: text
    fieldGroup: null
    handle: paymentTitle
    instructions: ''
    name: Title
    searchable: true
    settings:
      charLimit: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: ''
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\PlainText
  8ac9d37c-4f05-486a-84e6-2d59838d6ccb:
    contentColumnType: integer(10)
    fieldGroup: null
    handle: yearlyPayment
    instructions: (Optional)
    name: 'Yearly Payment'
    searchable: true
    settings:
      decimals: '0'
      max: ''
      min: '0'
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Number
  9b679f54-11f0-4985-975f-c94a316e3a2a:
    contentColumnType: text
    fieldGroup: null
    handle: monthlyPaymentByline
    instructions: 'ex: "current members only"'
    name: 'Monthly Payment Byline'
    searchable: true
    settings:
      charLimit: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: ''
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\PlainText
  b0cf3b3c-aac9-48d9-8c70-6b77edb044da:
    contentColumnType: text
    fieldGroup: null
    handle: monthlyPaymentStripePlanId
    instructions: 'The Stripe plan ID assigned to the corresponding subscription plan (ex: ''p001'')'
    name: 'Monthly Payment Stripe Plan Id'
    searchable: true
    settings:
      charLimit: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  d67b0672-6bc9-4767-9024-9006ff629216:
    contentColumnType: string
    fieldGroup: null
    handle: features
    instructions: 'An unordered list of features (select a bulleted list)'
    name: Features
    searchable: true
    settings:
      availableTransforms: ''
      availableVolumes: ''
      cleanupHtml: '1'
      columnType: text
      configFile: ''
      purifyHtml: '1'
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  ea18bac6-1587-4544-903f-15082de1333e:
    contentColumnType: text
    fieldGroup: null
    handle: yearlyPaymentDiscount
    instructions: 'The displayed discount, if applicable (ex: "2 months free!")'
    name: 'Yearly Payment Discount'
    searchable: true
    settings:
      charLimit: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: payment
name: payment
sortOrder: 1
