field: dd868fe1-3a50-4146-be40-157b12e3f0dc
fieldLayouts:
  28c68c2a-8153-49e8-8042-fda4324582bc:
    tabs:
      -
        fields:
          8d680780-bfde-41eb-a82a-724fa1d17ffa:
            required: false
            sortOrder: 2
          86088f94-8014-4bfa-89fb-966ae7cee523:
            required: false
            sortOrder: 1
        name: Content
        sortOrder: 1
fields:
  8d680780-bfde-41eb-a82a-724fa1d17ffa:
    contentColumnType: string
    fieldGroup: null
    handle: embed
    instructions: ''
    name: Embed
    searchable: true
    settings:
      allowedKinds: null
      defaultUploadLocationSource: 'volume:cd389634-6297-4886-ac1a-17f7ff2050c8'
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: ''
      restrictFiles: ''
      selectionLabel: 'Choose an embed'
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:6b3a49f8-4ed5-4a69-86eb-7b2fa0d422f6'
      singleUploadLocationSubpath: '{owner.slug}'
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: true
      validateRelatedElements: ''
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  86088f94-8014-4bfa-89fb-966ae7cee523:
    contentColumnType: boolean
    fieldGroup: null
    handle: expanded
    instructions: 'Setting this field to "on" will make the video expand outside the content container.'
    name: 'Expanded?'
    searchable: true
    settings:
      default: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
handle: video
name: Video
sortOrder: 5
