fieldLayouts:
  3eaaee9a-85ba-4c0a-bb0f-b05f51272ec2:
    tabs:
      -
        elements:
          -
            instructions: null
            label: ''
            type: craft\fieldlayoutelements\EntryTitleField
          -
            fieldUid: b0aefac7-6c72-4693-bb5a-2e79c46dd012
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 60fb224d-1163-4fda-8ccc-ec5f35830998
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 348f54c4-b833-4ced-bf8a-da9b48e36232
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: aaf771f5-2db7-4257-b26d-b6ca2a58f2c8
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 604b3172-76dc-4162-a081-4f0566cd981b
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: Default
        sortOrder: 1
handle: blog
hasTitleField: false
name: Ideas
section: 47e80b5c-8440-4621-8148-e9a56745e412
sortOrder: 1
titleFormat: '{section.name|raw}'
