fieldLayouts:
  467ee4e0-db5f-4d02-9403-f8b5839b8b76:
    tabs:
      -
        elements:
          -
            instructions: null
            label: Title
            type: craft\fieldlayoutelements\EntryTitleField
          -
            fieldUid: b0aefac7-6c72-4693-bb5a-2e79c46dd012
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 60fb224d-1163-4fda-8ccc-ec5f35830998
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 348f54c4-b833-4ced-bf8a-da9b48e36232
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: aaf771f5-2db7-4257-b26d-b6ca2a58f2c8
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: b6085a80-628f-4124-b670-314554126e4a
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: bb3370b5-8dad-4734-b503-b8b3b1b31338
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: Main
        sortOrder: 1
      -
        elements:
          -
            fieldUid: 8dd0581c-6902-4a9c-8ddd-e11ce7656351
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 1b46cfbb-c65a-4e89-afd3-750e238e31c1
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 7a978b7f-cab5-448c-88dc-d4e1a9d281cf
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: SEO
        sortOrder: 2
handle: index
hasTitleField: true
name: Index
section: e15c85a7-c70b-4d37-9227-c796679485fb
sortOrder: 2
titleFormat: ''
