fieldLayouts:
  bb657509-980d-4bf6-a50e-3fb445026747:
    tabs:
      -
        elements:
          -
            instructions: null
            label: Title
            type: craft\fieldlayoutelements\EntryTitleField
          -
            fieldUid: b0aefac7-6c72-4693-bb5a-2e79c46dd012
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 39037932-db05-465e-aa9f-ac995dcf52a3
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 0742d16d-ff12-44c8-9946-48094b611af3
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: b20b524d-39a1-465c-8779-3343f105238a
            required: true
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 2a183104-63d4-445d-9e90-de8bcd9938c4
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 50364b57-8731-453d-b212-32fd8d30c25a
            required: true
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 39a42cdc-d4b3-413a-affc-b6cb90cd0e99
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: cf9835fc-20c9-4837-82e8-ec16f965f65f
            required: true
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 687a30fa-2f0c-44ad-85bd-0c87ffaec0c4
            required: true
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 9628cfbe-7a5e-4469-82f2-63eff08a0681
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 755b777a-d10c-4321-9223-644f74eec81b
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: fbd80904-a7d9-456b-8cd7-e08ad76a867f
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: Main
        sortOrder: 1
      -
        elements:
          -
            fieldUid: 0d3e14a2-0c82-4a5f-b7ac-4e7ce75f352e
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: 'Content Blocks'
        sortOrder: 2
      -
        elements:
          -
            fieldUid: b16265b0-cb4e-4558-8cc7-36917aa93b69
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: 'Legacy Content'
        sortOrder: 3
      -
        elements:
          -
            fieldUid: 8dd0581c-6902-4a9c-8ddd-e11ce7656351
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 7a978b7f-cab5-448c-88dc-d4e1a9d281cf
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: SEO
        sortOrder: 4
handle: resources
hasTitleField: true
name: resources
section: b04c9ca0-ec19-4957-9463-e561c6cbe987
sortOrder: 1
titleFormat: ''
