fieldLayouts:
  48f51e86-0d19-4e69-a1db-ddbcbd28118b:
    tabs:
      -
        fields:
          6b5df7ea-0478-4276-9b48-a9117c3d1013:
            required: false
            sortOrder: 1
        name: Settings
        sortOrder: 1
handle: ageGroups
name: 'Age Groups'
siteSettings:
  84ea1cc0-8139-4b33-b94a-1c02700fc1ef:
    hasUrls: true
    template: resources/_browse
    uriFormat: 'resources/all?age={slug}'
  ed2e38d9-d86c-40c4-b682-df89fc90f62d:
    hasUrls: true
    template: resources/_browse
    uriFormat: 'recursos/todo?age={slug}'
structure:
  maxLevels: 1
  uid: aaf07168-433c-44b2-b3c3-abd62c021ac2
