fieldLayouts:
  23e6df92-e48d-46be-a220-c0b43192ff84:
    tabs:
      -
        fields:
          32044766-4b09-4e5c-a620-b18d4dbe3ffb:
            required: false
            sortOrder: 1
        name: Default
        sortOrder: 1
handle: ideasPostTypes
name: 'Ideas Post Types'
siteSettings:
  84ea1cc0-8139-4b33-b94a-1c02700fc1ef:
    hasUrls: true
    template: ideas/_type.html
    uriFormat: '{% if object.level == 1 %}type/{slug}{% else %}{parent.uri}/{slug}{% endif %}'
  ed2e38d9-d86c-40c4-b682-df89fc90f62d:
    hasUrls: true
    template: ideas/_type.html
    uriFormat: '{% if object.level == 1 %}tipo/{slug}{% else %}{parent.uri}/{slug}{% endif %}'
structure:
  maxLevels: null
  uid: 5eb49ffd-41f9-4a18-a7f9-79adfae8e21c
