handle: ideasCategories
name: 'Ideas Categories'
siteSettings:
  84ea1cc0-8139-4b33-b94a-1c02700fc1ef:
    hasUrls: true
    template: ideas/_browse
    uriFormat: 'ideas/all?category={slug}'
  ed2e38d9-d86c-40c4-b682-df89fc90f62d:
    hasUrls: true
    template: ideas/_browse
    uriFormat: 'ideas/todo?category={slug}'
structure:
  maxLevels: null
  uid: 43070767-1687-4312-991d-57f6651c8a22
