handle: resourcesTopics
name: 'Resources Topics'
siteSettings:
  84ea1cc0-8139-4b33-b94a-1c02700fc1ef:
    hasUrls: true
    template: resources/_browse
    uriFormat: 'resources/all?topic={slug}'
  ed2e38d9-d86c-40c4-b682-df89fc90f62d:
    hasUrls: true
    template: resources/_browse
    uriFormat: 'recursos/todo?topic={slug}'
structure:
  maxLevels: null
  uid: d7d16de7-9589-4298-9703-1bc2116140e6
