fieldLayouts:
  e6863704-f4d5-49eb-b90c-c4b3ca7c0a9e:
    tabs:
      -
        fields:
          033c51c3-9ce3-4ca5-9be9-a957bec922bf:
            required: false
            sortOrder: 2
          59634ba7-ce29-47f3-8f83-30d2037eeacb:
            required: false
            sortOrder: 1
        name: Settings
        sortOrder: 1
handle: posts
hasUrls: true
name: Posts
settings:
  path: uploads/posts/
sortOrder: 12
type: craft\volumes\Local
url: /uploads/posts/
