contentColumnType: string
fieldGroup: 9aec6670-8753-4f2e-91d5-03ff2b4f3ef6
handle: bannerImage
instructions: 'The main page banner image.'
name: 'Banner Image'
searchable: true
settings:
  allowedKinds:
    - image
  defaultUploadLocationSource: 'volume:cd389634-6297-4886-ac1a-17f7ff2050c8'
  defaultUploadLocationSubpath: ''
  limit: '1'
  localizeRelations: false
  restrictFiles: '1'
  selectionLabel: 'Choose banner image'
  singleUploadLocationSource: 'volume:6c50eae1-ceb0-4b11-8e50-b8544c8cbc69'
  singleUploadLocationSubpath: '{slug}/'
  sources: '*'
  targetSiteId: 84ea1cc0-8139-4b33-b94a-1c02700fc1ef
  useSingleFolder: '1'
  viewMode: large
translationKeyFormat: null
translationMethod: none
type: craft\fields\Assets
