contentColumnType: string
fieldGroup: 9aec6670-8753-4f2e-91d5-03ff2b4f3ef6
handle: featuredNews
instructions: ''
name: 'Featured News'
searchable: true
settings:
  contentTable: '{{%matrixcontent_featurednews}}'
  maxBlocks: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: none
type: craft\fields\Matrix
