contentColumnType: string
fieldGroup: c07eca58-32d2-42c5-9bc5-0149d5f91a25
handle: ideasBannerImage
instructions: 'The featured image used on the blog listing page and the giant banner image at the top of the post.'
name: 'Banner Image'
searchable: true
settings:
  allowedKinds:
    - image
  defaultUploadLocationSource: 'volume:6b3a49f8-4ed5-4a69-86eb-7b2fa0d422f6'
  defaultUploadLocationSubpath: '{owner.slug}'
  limit: '1'
  localizeRelations: ''
  restrictFiles: '1'
  selectionLabel: ''
  showUnpermittedFiles: false
  showUnpermittedVolumes: true
  singleUploadLocationSource: 'volume:cd389634-6297-4886-ac1a-17f7ff2050c8'
  singleUploadLocationSubpath: ''
  source: null
  sources:
    - 'volume:6b3a49f8-4ed5-4a69-86eb-7b2fa0d422f6'
  targetSiteId: 84ea1cc0-8139-4b33-b94a-1c02700fc1ef
  useSingleFolder: false
  validateRelatedElements: ''
  viewMode: large
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
