contentColumnType: string
fieldGroup: 9aec6670-8753-4f2e-91d5-03ff2b4f3ef6
handle: introSections
instructions: 'Sections that appear in the page intro underneath the page description'
name: 'Intro Sections'
searchable: true
settings:
  contentTable: '{{%matrixcontent_introsections}}'
  maxBlocks: '2'
  minBlocks: ''
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
