contentColumnType: text
fieldGroup: b8065821-73bc-41b6-9331-08c71b8228ff
handle: linkedinUrl
instructions: 'ex: http://linkedin.com/ednavigator'
name: 'LinkedIn Url'
searchable: true
settings:
  charLimit: ''
  columnType: text
  initialRows: '4'
  multiline: ''
  placeholder: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
