contentColumnType: string
fieldGroup: b8065821-73bc-41b6-9331-08c71b8228ff
handle: locations
instructions: 'A list of the Ed Navigator locations. Used throughout the site, primarily to organize the staff by location.'
name: Locations
searchable: true
settings:
  contentTable: '{{%matrixcontent_locations}}'
  maxBlocks: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: none
type: craft\fields\Matrix
