contentColumnType: string
fieldGroup: a6a6a3b2-033c-4402-91de-5001380f4f70
handle: ourApproach
instructions: ''
name: 'Our Approach'
searchable: true
settings:
  contentTable: '{{%matrixcontent_ourapproach}}'
  maxBlocks: null
  propagationMethod: none
translationKeyFormat: null
translationMethod: none
type: craft\fields\Matrix
