contentColumnType: string
fieldGroup: b8065821-73bc-41b6-9331-08c71b8228ff
handle: physicalAddress
instructions: 'The EdNavigator physical address that appears in the footer'
name: 'Physical Address'
searchable: true
settings:
  contentTable: '{{%matrixcontent_physicaladdress}}'
  maxBlocks: '1'
  propagationMethod: all
translationKeyFormat: null
translationMethod: none
type: craft\fields\Matrix
