contentColumnType: string
fieldGroup: c76d81fd-6544-4c75-a833-9f6f2a7a0149
handle: positions
instructions: 'Open Positions'
name: Positions
searchable: true
settings:
  contentTable: '{{%matrixcontent_positions}}'
  maxBlocks: null
  propagationMethod: none
translationKeyFormat: null
translationMethod: none
type: craft\fields\Matrix
