contentColumnType: text
fieldGroup: c76d81fd-6544-4c75-a833-9f6f2a7a0149
handle: principlesSectionLabel
instructions: 'The label of the principles section'
name: 'Principles Section Label'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: text
  initialRows: '4'
  multiline: ''
  placeholder: ''
translationKeyFormat: null
translationMethod: language
type: craft\fields\PlainText
