contentColumnType: string
fieldGroup: 0200d286-aa37-4a58-9853-7f8a1aeb6cc3
handle: resourcesBannerImage
instructions: 'The featured image used on the resources listing page and the giant banner image at the top of the post.'
name: 'Banner Image'
searchable: true
settings:
  allowedKinds:
    - image
  defaultUploadLocationSource: 'volume:1e3bbacb-6818-4f7f-8516-ae22e47c8b82'
  defaultUploadLocationSubpath: '{slug}/'
  limit: '1'
  localizeRelations: false
  restrictFiles: '1'
  selectionLabel: ''
  singleUploadLocationSource: 'volume:1e3bbacb-6818-4f7f-8516-ae22e47c8b82'
  singleUploadLocationSubpath: ''
  sources:
    - 'volume:1e3bbacb-6818-4f7f-8516-ae22e47c8b82'
  useSingleFolder: ''
  viewMode: large
translationKeyFormat: null
translationMethod: none
type: craft\fields\Assets
