contentColumnType: string
fieldGroup: 0200d286-aa37-4a58-9853-7f8a1aeb6cc3
handle: resourceTopic
instructions: ''
name: 'Resource Topic'
searchable: true
settings:
  branchLimit: '1'
  localizeRelations: false
  selectionLabel: ''
  source: 'group:7f19df16-7584-4d94-a3f7-6aa14f45630b'
translationKeyFormat: null
translationMethod: none
type: craft\fields\Categories
