contentColumnType: string
fieldGroup: a6a6a3b2-033c-4402-91de-5001380f4f70
handle: resultsText
instructions: ''
name: 'Results Text'
searchable: true
settings:
  availableTransforms: ''
  availableVolumes: ''
  cleanupHtml: '1'
  columnType: text
  configFile: Standard.json
  purifierConfig: ''
  purifyHtml: '1'
translationKeyFormat: null
translationMethod: site
type: craft\redactor\Field
