contentColumnType: text
fieldGroup: 906608b2-91ed-4a3f-af22-d10f34202903
handle: sustainableResultsText
instructions: ''
name: 'Sustainable Results Text'
searchable: true
settings:
  availableTransforms: ''
  availableVolumes: ''
  cleanupHtml: true
  columnType: text
  purifierConfig: ''
  purifyHtml: '1'
  redactorConfig: Standard.json
  removeEmptyTags: '1'
  removeInlineStyles: '1'
  removeNbsp: '1'
translationKeyFormat: null
translationMethod: language
type: craft\redactor\Field
