contentColumnType: text
fieldGroup: 906608b2-91ed-4a3f-af22-d10f34202903
handle: sustainableResultsHeadline
instructions: ''
name: 'Sustainable Results Headline'
searchable: false
settings:
  charLimit: ''
  code: ''
  columnType: text
  initialRows: '2'
  multiline: '1'
  placeholder: ''
translationKeyFormat: null
translationMethod: language
type: craft\fields\PlainText
