contentColumnType: text
fieldGroup: b8065821-73bc-41b6-9331-08c71b8228ff
handle: twitterUrl
instructions: 'ex: http://twitter.com/ednavigate'
name: 'Twitter Url'
searchable: true
settings:
  charLimit: ''
  columnType: text
  initialRows: '4'
  multiline: ''
  placeholder: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
