fieldLayouts:
  dc4f647a-1b5f-4b44-b437-37d553fc1e11:
    tabs:
      -
        fields:
          1b46cfbb-c65a-4e89-afd3-750e238e31c1:
            required: false
            sortOrder: 3
          7a978b7f-cab5-448c-88dc-d4e1a9d281cf:
            required: false
            sortOrder: 1
          8dd0581c-6902-4a9c-8ddd-e11ce7656351:
            required: false
            sortOrder: 2
        name: Content
        sortOrder: 1
handle: globalSeo
name: 'Global SEO'
