enableVersioning: true
handle: homepage
name: Homepage
previewTargets:
  -
    label: 'Primary entry page'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  84ea1cc0-8139-4b33-b94a-1c02700fc1ef:
    enabledByDefault: true
    hasUrls: true
    template: index
    uriFormat: __home__
  ed2e38d9-d86c-40c4-b682-df89fc90f62d:
    enabledByDefault: true
    hasUrls: true
    template: index
    uriFormat: __home__
type: single
