enableVersioning: false
handle: navigation
name: Navigation
previewTargets:
  -
    label: 'Primary entry page'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  84ea1cc0-8139-4b33-b94a-1c02700fc1ef:
    enabledByDefault: true
    hasUrls: true
    template: ''
    uriFormat: 'navigation/{slug}'
  ed2e38d9-d86c-40c4-b682-df89fc90f62d:
    enabledByDefault: true
    hasUrls: true
    template: ''
    uriFormat: 'navigation/{slug}'
structure:
  maxLevels: 2
  uid: ada7d82e-b202-4036-9eb8-a2286e6ac1f2
type: structure
