enableVersioning: true
handle: whoWeAre
name: 'Who We Are'
previewTargets:
  -
    label: 'Primary entry page'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  84ea1cc0-8139-4b33-b94a-1c02700fc1ef:
    enabledByDefault: true
    hasUrls: true
    template: who-we-are
    uriFormat: '{% if object.level == 1 %}who-we-are{% else %}{parent.uri}/{slug}{% endif %}'
  ed2e38d9-d86c-40c4-b682-df89fc90f62d:
    enabledByDefault: true
    hasUrls: true
    template: who-we-are
    uriFormat: '{% if object.level == 1 %}quienes-somos{% else %}{parent.uri}/{slug}{% endif %}'
structure:
  maxLevels: 2
  uid: 344355f6-b139-4be7-8695-0380a4b83d75
type: structure
